### PR TITLE
Improvements on Bounding Boxes NMS function and final image plotting

### PR DESCRIPTION
**Pull request by GrunCrow**
Bounding Boxes: sorting them by max by class, comparing the closest ones by class

Plotting: Added labels and score per Bounding Box (category id + score) and a legend to better visualize it.

### CODE REVIEW

**Comment by GrunCrow** [comment]
image

This is how the plotting would look like

**Comment by GrunCrow** [comment]
Output example for the given image:

```
[{"image_id": "multispecies", "category_id": 12, "bbox": [1745.129150390625, 281.81005859375, 2396.85546875, 703.0232543945312], "score": 0.9463137984275818, "activations": [6.7707806010730565e-06, 0.00015133617853280157, 7.2852958510338794e-06, 5.356243491405621e-06, 3.157063929393189e-06, 6.083472726459149e-06, 0.000238957378314808, 7.911457942100242e-06, 6.92849644110538e-05, 0.00018557647126726806, 1.0601332178339362e-05, 9.332477020507213e-06, 0.9463137984275818, 3.962740083807148e-05, 9.315516945207492e-05]}, {"image_id": "multispecies", "category_id": 14, "bbox": [415.4966735839844, 707.5853271484375, 902.4221801757812, 1022.4902954101562], "score": 0.9306128025054932, "activations": [1.0245989869872574e-06, 1.4873347936372738e-05, 9.60783290793188e-06, 7.768529030727223e-06, 6.864834722364321e-05, 7.189803727669641e-05, 0.0009384485892951488, 3.7414031339721987e-06, 6.7493519964045845e-06, 4.8665689973859116e-05, 4.247521428624168e-05, 0.00024027812469284981, 0.00016996944032143801, 5.876001523574814e-05, 0.9306128025054932]}, {"image_id": "multispecies", "category_id": 14, "bbox": [2080.0556640625, 750.0076293945312, 2400.0, 1220.424560546875], "score": 0.8887741565704346, "activations": [1.8715643363975687e-06, 9.62185877142474e-05, 1.6619549569441006e-05, 2.7507108825375326e-05, 9.888372733257711e-05, 3.9956743421498686e-05, 0.0003135375154670328, 8.138885277730878e-06, 4.145500861341134e-05, 0.00010777584975585341, 3.819121775450185e-05, 0.00018825638107955456, 0.001617119531147182, 0.0012858833651989698, 0.8887741565704346]}, {"image_id": "multispecies", "category_id": 12, "bbox": [792.1112670898438, 429.4925231933594, 993.809326171875, 562.9796142578125], "score": 0.8828365802764893, "activations": [7.538756108260714e-07, 3.0993312975624576e-05, 2.994058149852208e-06, 2.8474685223045526e-06, 1.6626852783474533e-08, 1.907098294395837e-06, 3.738283703569323e-05, 1.414297912560869e-06, 4.192385313217528e-05, 9.931852673616959e-07, 5.059611794422381e-06, 2.126376421074383e-05, 0.8828365802764893, 1.2133217751397751e-05, 1.733128010528162e-05]}, {"image_id": "multispecies", "category_id": 12, "bbox": [1050.6824951171875, 425.80731201171875, 1183.6131591796875, 493.144775390625], "score": 0.6393409967422485, "activations": [6.861393558210693e-06, 0.0005025968421250582, 1.6627066088403808e-06, 3.933722109650262e-05, 1.517699274700135e-06, 4.769147199112922e-05, 0.00023909089213702828, 7.949599421408493e-06, 0.0008411300950683653, 3.0162926123011857e-05, 1.584635720064398e-05, 3.563113205018453e-05, 0.6393409967422485, 2.9879636713303626e-05, 0.00019891004194505513]}]
```

**Comment by GrunCrow** [comment]
I just found out image_id is not being updated in the json, working on it!

**Review by justinkay — APPROVED** [review]
Nice work @GrunCrow :D

**Pull request merged**
